on: [push]
name: Azure ARM
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

      # Checkout code
    - uses: actions/checkout@main

      # Log into Azure
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Deploy ARM template
    - name: Run ARM deploy
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
        resourceGroupName: ${{ secrets.AZURE_RG }}
        template: ./AKS/ARM-template/azuredeploy.json
        parameters: servicePrincipalClientId=${{ secrets.AKS_SP_ID }} servicePrincipalClientSecret=${{ secrets.AKS_SP_PW }} sshRSAPublicKey=${{ secrets.SSH_PUBLIC_KEY }} linuxAdminUsername=adminjer dnsPrefix=workshop20201125 clusterName=workshop20201125

      # output containerName variable from template
    - run: echo ${{ steps.deploy.outputs.containerName }}
